### PR TITLE
Y2016 tux

### PR DESCRIPTION
**Pull request by Tux**
This should be it. I received no feedback at all in the process, so I hope this fits the expectations

### CODE REVIEW

**Comment by Tux** [comment]
@JJ is this work merge-able or too intrusive?

**Comment by JJ** [comment]
The problem is that I see too many commits that shouldn't be there because they are *already* in `y2016`... Last time I merged by hand, locally, and then pushed it back to the y2016 branch. Please take a look to see if you can find what's wrong and if not I'll check back again.

**Comment by perlpunk** [comment]
my general suggestion:
always rebase your local branch to the current y2016 before merging it. that makes the history soo much easier, and any following merges/rebases/conflict resolving.

**Comment by Tux** [comment]
I have created a new branch based on y2016 just for the spell checking. I'll do a PR there

**Comment by Tux** [comment]
I rebased on y2016 again

**Comment by 2shortplanks** [comment]
Old pull request

**Pull request closed without merging**
