### PR TITLE
And a star on top

### PR DESCRIPTION
**Pull request by bolangi**
Change Audio::Nama to Nama, first Nama in text links to manpage

### CODE REVIEW

**Comment by oalders** [comment]
I think the cleanest thing to do is just get the latest `main` and branch off of that. There's a lot of commits in here that are just muddying the waters. Right now I see 59 commits, but only one line has been changed. 🤔

**Comment by oalders** [comment]
This also has a merge conflict. Should both of the PRs for this article still be open?

**Comment by bolangi** [comment]
> This also has a merge conflict. Should both of the PRs for this article still be open?

I think since the article is published we can stop here. 

Thank you

-- 
Joel Roth

**Comment by oalders** [comment]
Ok, thanks! We can still make post-publish changes, but I'll close this for now.

**Pull request closed without merging**
