### PR TITLE
Y2016 from Tux

### PR DESCRIPTION
**Pull request by JJ**
I have moved @Tux 's stuff a little bit around, with files in `share/static` and the pod file in the `submission` dir. Also deleted a personal dictionary. I would say it's pretty much loyal to original slash location, but it would be OK if @Tux reviewed it before merging.
Also, I haven't seen actual links from the Santa.pod file to the files, so I have just left them like they are. Maybe a section reminding where to find the files would be OK.

### CODE REVIEW

**Comment by Tux** [comment]
There are no links to the files. They are there as "proof" of how things work. I can add links if you think that would improve the article

**Comment by JJ** [comment]
You probably should. It would be difficult to find them otherwise... Maybe
a link at the end of the article saying: You can find source to avoid cut
and paste here...

**Comment by Tux** [comment]
Should that be
```
The master elf showed his programmers the format of the wish-list he got from
the UK department, named L<C<wish-uk.csv>|share/static/wish-uk.csv>:
```
or
```
The master elf showed his programmers the format of the wish-list he got from
the UK department, named L<C<wish-uk.csv>|../share/static/wish-uk.csv>:
```

**Comment by JJ** [comment]
>
>
> The master elf showed his programmers the format of the wish-list he got from
> the UK department, named L<C<wish-uk.csv>|../share/static/wish-uk.csv>:
>
>
>
If it finally goes to `2016` I would say that's the one. But as long as you
insert the link, I think it will be easier to change when it's published
finally wherever.

**Pull request merged**
