### PR TITLE
smonff article for Perl Advent 2024

### PR DESCRIPTION
**Pull request by smonff**
It's called _"Stay focused and organised during the advent season"_. It tells the story of a team of elves who use modern work methodologies to improve their work life. Surprise, they use a Perl tool to take standup notes, and it's made with Object::Pad.  

- [x] I ran `t/article_pod.t`  
- [x]  I ran `codespell` and corrected typos
- [x] I checked it again because I am french 
- [x] I tested the code examples

`TODO` 
- [x] Release the module on the CPAN after renaming (`/Standup::Diary/App::Standup::Diary/`)
- [x] Check the links 

For #424.

### CODE REVIEW

**Comment by oalders** [comment]
Thank you for your contribution! I'm finding that blog articles which include images have much more compelling social media previews when the article is shared. Adding an image is by no means required and you should feel free to ignore this message entirely. However, if you'd like to add an image, it's as simple as:

* Adding the image to the `2024/share/static` folder like `2024/share/static/some-graphic.png`
* Including the image as HTML in your article

The HTML would look like:

```
=for :html
<img src="some-graphic.png">

```

The trailing blank line is important as that signals that the `HTML` section is finished.

Images can most certainly be AI generated. You should also feel free to use https://search.creativecommons.org/ in order to find CC images which can be freely shared. If you choose to go this route, please provide proper attribution when including the image, if attribution is required.

Most importantly, if you don't feel like doing this, then feel free to submit your article without an image. It's *your* article and *you* need to be happy with it.

**Comment by smonff** [comment]
I used search.creativecommons.org and I think I like this:

imagehttps://flickr.com/photos/aloha75/27771493216/in/photostream/

[Source](https://flickr.com/photos/aloha75/27771493216/in/photostream/), should be fine on the license aspect.

I'll update the MR accordingly right away.

If not appropriated, feel free to use anything better, but I would really prefer something _not_ AI generated, please.

**Comment by oalders** [comment]
Looks great!

**Comment by smonff** [comment]
I updated the article with the proposed image. 

The preview (`perl script/render-incoming.pl && http_this --autoindex out/2024/`) doesn't look great on the preview on my side, but it seems to use a different CSS as in the live version, so I assume it will be fine. Please ping me if it is not, in the worst case, I'll resize the image.

image

**Pull request merged**
