### PR TITLE
Add a build and deploy GH workflow

### LINKED ISSUE #3: write a "site builder" to build the static top-level HTML
Managing the site's top-level HTML files (FAQ, submission page, etc.) in HTML is pretty grody.  I've converted several of these files to Markdown.

Now we need a program that will, run from a git repo, write out the HTML files needed from those Markdown files.

It should have links to the previous calendars, the archive pages, and the Markdown-to-html-converted pages.  It should have the RSS feed.

### PR DESCRIPTION
**Pull request by oalders**
Closes #3 

Site is currently at https://perladvent.github.io/Perl-Advent/

### CODE REVIEW

**Comment by oalders** [comment]
The site doesn't want to be deployed to subfolder, so the archive links aren't currently correct.

**Comment by thibaultduponchelle** [comment]
> The site doesn't want to be deployed to subfolder, so the archive links aren't currently correct.

?

**Comment by oalders** [comment]
The site is now viewable at https://staging.perladvent.org/  There's still an issue of DNS propagation and TLS configuration after switching the name servers, but it's there.

Once we're happy, we can switch www to point at the new location.

**Comment by thibaultduponchelle** [comment]
🕺🏼

**Review by thibaultduponchelle — APPROVED** [review]

**Pull request merged**
