### PR TITLE
Some edits to Santa's Helpers Embrace the Shell

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
@openstrike @s1037989

### CODE REVIEW

**Review by s1037989 — CHANGES_REQUESTED** [review]
Thank you for making these edits!  Could you also rename the file, adding "s" to "helper"?

2022/incoming/santas-helpers-embrace-the-shell.pod

**Review by openstrike — APPROVED** [review]
Approved - thanks.

**Comment by thibaultduponchelle** [comment]
@s1037989 Done! Can you please approve :)

**Review by s1037989 — APPROVED** [review]
Looks great!  Thank you for your edits!

**Pull request merged**
