### PR TITLE
My contribution to Y2024 Advent Calendar

### LINKED ISSUE #438: Perl, my child, is love in Github Actions
Perl has been and is the glue that bind together many different and disparate command line applications; all and everyone can use it to create data munging pipelines that just work. That has made it a mainstay in many operating systems... Including those that can be found in Github workflow runners. These not only include Perl, but a good and nice series of Perl modules that will give you no work at all to create fast-and-dirty github actions that can be glued together, in the same way as Linux commands are.
But if that's not enough, you can always rely on CPAN and packers, as well as Github Action templates avaiable in GitHub. This article will be about that: what support is out there to create GitHub actions with Perl, and how to do it in no time flat, applying Perl love to your DevOps pipelines.

### PR DESCRIPTION
**Pull request by JJ**
And Merry Xmas everyone!
Closes #438

### CODE REVIEW

**Comment by oalders** [comment]
Thank you for your contribution! I'm finding that blog articles which include images have much more compelling social media previews when the article is shared. Adding an image is by no means required and you should feel free to ignore this message entirely. However, if you'd like to add an image, it's as simple as:

* Adding the image to the `2024/share/static` folder like `2024/share/static/some-graphic.png`
* Including the image as HTML in your article

The HTML would look like:

```
=for :html
<img src="some-graphic.png">

```

The trailing blank line is important as that signals that the `HTML` section is finished.

Images can most certainly be AI generated. You should also feel free to use https://search.creativecommons.org/ in order to find CC images which can be freely shared. If you choose to go this route, please provide proper attribution when including the image, if attribution is required.

Most importantly, if you don't feel like doing this, then feel free to submit your article without an image. It's *your* article and *you* need to be happy with it.

**Comment by oalders** [comment]
Thank you very much for your contribution. I have unfortunately come up against some time constraints and I don't have the resources to dedicate to another 12 or so proper article reviews. If we don't get a review in, your article will still get merged, but I'll likely only have time to look for typos and ensure formatting is mostly correct.

If you know of a peer who would be willing to review your work, I'd encourage you to ask them to leave a review on this pull request. If you find yourself with any extra time, feel free to self-assign any outstanding Advent pull request(s) and leave a helpful review. [The editing guidelines](https://github.com/perladvent/Perl-Advent/blob/main/EDITING.md) should be helpful in this regard.

Basically the situation this year is that most articles arrived in late November/early December, meaning that there is now a bottleneck at this time of year which is busy for many of us. This is not a judgement on anyone -- all articles are welcome and I always expect some to come in later in the game. In fact, there are still more articles to come which do not yet have pull requests.

In order to ensure that everyone's content gets a fair chance for review, I'm looking to cast a wider net. Hopefully spreading the effort around this way will help us continue the tradition of high value Advent articles in 2025.

**Review by oalders — APPROVED** [review]
Thanks, @JJ!

**Comment by oalders** [comment]
A really helpful article. Not sure if you know about this org: https://github.com/perl-actions Might be a good fit for the kinds of things you're working on.

**Comment by JJ** [comment]
Of course I know. I use it often, but in many cases, all you need is already in the runner.

**Comment by oalders** [comment]
Right. I guess I meant more if you were looking to increase the bus number on your repositories, they could also find a home there.

**Comment by JJ** [comment]
> Right. I guess I meant more if you were looking to increase the bus number on your repositories, they could also find a home there.

I didn't know you could apply for that...

**Pull request merged**
