### PR TITLE
Copy edits

### PR DESCRIPTION
**Pull request by petdance**
Nothing major.  A few mechanical fixes, some POD markup, and a couple of wordy sentences got trimmed down.

### CODE REVIEW

**Comment by petdance** [comment]
I've done something wrong here.  I'll recreate this with only my edits.

**Comment by petdance** [comment]
I'm not sure why this has all the other commits in the PR, but e785df037cba0484b1e4256f1e70f87ec7e681c2 and 089bce27272487070a03451e9d80742b5e3519d1 are the two that are actually mine.

**Comment by JJ** [comment]
I think it will have to be done by hand. Don't worry, we'll try to do it.

**Comment by 2shortplanks** [comment]
Cherry picked

**Pull request closed without merging**
