### PR TITLE
New article: Silent Mite

### PR DESCRIPTION
**Pull request by tobyink**

### CODE REVIEW

**Comment by PatrickCronin** [comment]
Hi @tobyink - I've been nominated to review your PR. Is it ready for review now, or should I hold off?

**Comment by tobyink** [comment]
Should be ready.

**Review by PatrickCronin — APPROVED** [review]
I love the article, as well as the idea for the tool. Neat! I have no suggestions for improvements or tweaks.

**Comment by tobyink** [comment]
I probably should have mentioned issue #157 in the PR.

**Comment by oalders** [comment]
> I have covid at the moment though so I'm blaming that for forgetting things like that.

I just had it a few weeks ago. I hope you feel better soon!

**Review by openstrike — APPROVED** [review]
This article is really well written - great job.

**Pull request merged**
