### PR TITLE
Create new articles in articles instead incoming. Harmonize script naming

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
# Main change
The script `new_article` does a good job but when it creates in `incoming` directory it does not make the article immediately ready for generation. I propose to create articles in `articles` with a date from available ones. It will enable to immediately preview articles by just typing `advcal -c advent.ini` (just need to force date with `--today`).

# Other changes
- Renaming scripts to match some sort or naming convention + add suffix 
- Add shebang + change permissions

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
@briandfoy

**Review by openstrike — COMMENTED** [review]
Doesn't this create a race condition? If 2 users clone the repo and both run new-article.pl then they will be creating identically named files in the tree. Won't that make merging their PRs more difficult rather than less?

**Comment by thibaultduponchelle** [comment]
Yes.. 

There should be a better solution to this.

**Comment by briandfoy** [comment]
No need to tag me on things. If there's something I've contributed that you need to change, just go for it.

**Pull request closed without merging**
