### PR TITLE
First draft of Text::Hogan y2015 submission

### PR DESCRIPTION
**Pull request by kaoru**
PR against the right branch this time!

-----------------

Here's my first draft :-)

Is there an easy way I can render the submission on my side and see how it looks? Specifically I wasn't sure if I got the link syntax correct and wanted to check that.

I also think it might be a bit long. Do you see any opportunities for trimming? Be brutal :-)

Thanks!

### CODE REVIEW

**Comment by rjbs** [comment]
It's a bit convoluted.  You should be able to:

* install WWW::AdventCalendar
* copy your file to ./2014/src/2014-12-01.pod
* run:  advcal -c advent.ini 
* look at the rendered file in ./out/2014-12-01.html

Generally when I look at calendar entries, I generate the year-to-come (2015, now) with the `--today` switch set to the future.  Then I can see what the calendar will look like.

**Comment by 2shortplanks** [comment]
Hi @kaoru, any change in this?  The output needs to be turned into pod format....

**Comment by kaoru** [comment]
@rjbs ah, "there's a CPAN module for that", I should have known :-) Thanks for the steps, you meant `articles` not `src` in your first bullet but the rest worked nicely.

@2shortplanks oh, I looked at some other file and convinced myself I had the right format. D'oh. Proper POD incoming...

**Comment by kaoru** [comment]
@2shortplanks I updated it with POD and #!perl for the syntax highlighting of code sections. I tried #!js and #!javascript for the JavaScript code segment but neither worked right - do you know if it's an option at all?

**Comment by rjbs** [comment]
For JS, you need to use the Vim highlighter:

```
    #!vim javascript
   var addone = (x) => x + 1;
```

**Comment by 2shortplanks** [comment]
You know this would make a good advent calendar entry

http://perladvent.org/2013/2013-12-20.html

**Comment by kaoru** [comment]
@rjbs @2shortplanks ah hah! New PR incoming

**Pull request merged**
