### PR TITLE
Redirect 2022

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Current [perladvent.org](https://perladvent.org) just say "The Calendar should be posted shortly." so I propose to redirect for now to 2022 calendar. I can't remember how it was done the other years...

It's a bit clunky but it does the job :shrug:

### CODE REVIEW

**Review by briandfoy — CHANGES_REQUESTED** [review]
Did you mean to request the *.bak file?

**Comment by thibaultduponchelle** [comment]
I kept the .bak file is just for putting it back after the advent season.

But today, [perladvent.org](https://perladvent.org) is showing (whereas we already have an article published):
advent

At least we should have a link to 2022 or we can redirect during december (my proposal)

**Comment by openstrike** [comment]
Given that the calendar is ready but not linked and that it's the 1st already, I think that the clunky redirect is better than the current home page.

IMO, there's no need to keep the .bak file since it's all under git anyway.

**Review by oalders — APPROVED** [review]
I guess I had just expected this page to disappear on Dec 1st. 🤷🏻‍♂️ 

Ideally we could also just have the GH site builder do this, but this is a serviceable fix for today. Thanks @thibaultduponchelle!

**Pull request merged**
