### PR TITLE
Ordering

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
I propose this ordering for the 15 first articles

### CODE REVIEW

**Comment by oalders** [comment]
My apologies. I merged the article edits for `what-did-santa-forget` and we now have a merge conflict.

**Review by oalders — APPROVED** [review]
🎅

**Review by briandfoy — APPROVED** [review]
Looks good to me, but I'll let you merge it.

**Comment by thibaultduponchelle** [comment]
Something seems wrong since I still see some articles (that I just moved) in incoming...

**Pull request merged**
