### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by oalders**
- Clean up README
- Add note about updating archives
- Update archives.yaml
- Ensure article tests include current year
- New index.html file

With this change we no longer need to delete the index file in December.

### CODE REVIEW

**Comment by oalders** [comment]
Bildschirmfoto 2024-02-21 um 9 58 46 AM
Bildschirmfoto 2024-02-21 um 9 59 05 AM

**Comment by oalders** [comment]
This was ~90% done by CoPilot. 🚀

**Comment by thibaultduponchelle** [comment]
I would love to have the archives years links listed directly on the index page.
It could maybe follow the same sort of calendar style (not just a list of ul/li) than what we have on each year indexes. 
Not using same generator though, maybe not that easy.

What do you think? @oalders @openstrike

**Comment by oalders** [comment]
It would make for a nicer page for sure. I think we could still merge the above as an improvement and then iterate on the front page. Right now, it looks pretty wacky in production.

**Pull request merged**
