### PR TITLE
Remove duplicate css

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
These files are just duplicates of css that are generated by WWW::AdventCalendar.
They should only contain extra styles.
I did not remove them because they are still included (404) even if not present at generation time.

### CODE REVIEW

**Comment by oalders** [comment]
There was a small change in 332. Is that getting removed here? I'm on my phone, so haven't checked.

**Comment by thibaultduponchelle** [comment]
It will be there in `style.css` (instead `2023.css`) thanks to https://github.com/perladvent/WWW-AdventCalendar/pull/1

**Comment by thibaultduponchelle** [comment]
Oh wait, https://github.com/perladvent/WWW-AdventCalendar/pull/1 is not merged yet

**Comment by thibaultduponchelle** [comment]
Actually, we can configure for "extra" css or no "extra" css at all in `advent.ini`
I updated this pull request to do this way.

But it's still not ready to merge until https://github.com/perladvent/WWW-AdventCalendar/pull/1 is sorted out to preserve @bbrtj improvement from #332

**Comment by thibaultduponchelle** [comment]
Now waiting for https://github.com/perladvent/WWW-AdventCalendar/pull/3 to be merged first

**Review by oalders — APPROVED** [review]

**Pull request merged**
