### PR TITLE
fix a handful of typos; add a spellchecker as well

### PR DESCRIPTION
**Pull request by sergeyromanov**
It's a @PerlDancer's advent calendar inspired spellchecker.

I ran it just against 2015 edition, since skip list would be enormous otherwise :)

### CODE REVIEW

**Comment by 2shortplanks** [comment]
Awesome. In my defence...the future articles aren't fully edited yet ;-)

Can you add AJAJ to the stop list (asynchronous JavaScript and JSON) and resubmit? I'm not in front of a computer right now to do the fiddling

**Comment by sergeyromanov** [comment]
@2shortplanks you got it! :)

**Comment by sergeyromanov** [comment]
sorry -- amend didn't went well. I'll resubmit a micro fix in another PR :)

**Comment by sergeyromanov** [comment]
An advent article on this would be so meta :D

**Pull request merged**
