### PR TITLE
Using Net::Clacks to monitor Santas workshop output

### PR DESCRIPTION
**Pull request by cavac**
Santa is on a tight deadline. He needs to monitor his workshop output minute-by-minute. So he chooses to use Net::Clacks to centrally count every present produced in sort-of real time...

### CODE REVIEW

**Comment by cavac** [comment]
It's a new contribution.

You may have to take a quick peak before using it, my english is unfortunately less than perfect.

**Comment by oalders** [comment]
Thank you for your contribution! I'm finding that blog articles which include images have much more compelling social media previews when the article is shared. Adding an image is by no means required and you should feel free to ignore this message entirely. However, if you'd like to add an image, it's as simple as:

* Adding the image to the `2024/share/static` folder like `2024/share/static/some-graphic.png`
* Including the image as HTML in your article

The HTML would look like:

```
=for :html
<img src="some-graphic.png">

```

The trailing blank line is important as that signals that the `HTML` section is finished.

Images can most certainly be AI generated. You should also feel free to use https://search.creativecommons.org/ in order to find CC images which can be freely shared. If you choose to go this route, please provide proper attribution when including the image, if attribution is required.

Most importantly, if you don't feel like doing this, then feel free to submit your article without an image. It's *your* article and *you* need to be happy with it.

**Comment by oalders** [comment]
Thank you very much for your contribution. I have unfortunately come up against some time constraints and I don't have the resources to dedicate to another 12 or so proper article reviews. If we don't get a review in, your article will still get merged, but I'll likely only have time to look for typos and ensure formatting is mostly correct.

If you know of a peer who would be willing to review your work, I'd encourage you to ask them to leave a review on this pull request. If you find yourself with any extra time, feel free to self-assign any outstanding Advent pull request(s) and leave a helpful review. [The editing guidelines](https://github.com/perladvent/Perl-Advent/blob/main/EDITING.md) should be helpful in this regard.

Basically the situation this year is that most articles arrived in late November/early December, meaning that there is now a bottleneck at this time of year which is busy for many of us. This is not a judgement on anyone -- all articles are welcome and I always expect some to come in later in the game. In fact, there are still more articles to come which do not yet have pull requests.

In order to ensure that everyone's content gets a fair chance for review, I'm looking to cast a wider net. Hopefully spreading the effort around this way will help us continue the tradition of high value Advent articles in 2025.

**Review by oalders — APPROVED** [review]
Thanks, @cavac!

**Pull request merged**
