### PR TITLE
Star

### PR DESCRIPTION
**Pull request by bolangi**
Christmas storyline, edits

### CODE REVIEW

**Comment by bolangi** [comment]
Second try, yes quite a few edits. Thank you for your patience!

**Review by oalders — APPROVED** [review]

**Comment by oalders** [comment]
This has a merge conflict which needs to be resolved.

**Comment by bolangi** [comment]
Thank you, I see the article is published!

On Mon, Dec 18, 2023 at 07:42:29AM -0800, Olaf Alders wrote:
> This has a merge conflict which needs to be resolved. 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/perladvent/Perl-Advent/pull/387#issuecomment-1860849672
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Joel Roth

**Comment by bolangi** [comment]
Great to see the high quality of articles this year!

I'm ready to try another pull request. To avoid merge conflicts
I'm planning to:

1. Pull to my fork.
2. Pull to my local repo
3. Make a new branch
4. Open pull request
5. Push changes, just once, till the PR is merged. 

Do you have any suggestions?

Thank you


-- 
Joel Roth

**Pull request closed without merging**
